// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SCMDWH.Shared.Models;

public partial class GlobalAppUsers
{



    [Required(ErrorMessage = "User Name is required.")]
 
    public string UserName { get; set; }

    
    public string Email { get; set; }

    [MaxLength(11)]
    public string Mobile { get; set; }
   
    public string CreatedBy { get; set; }

    public DateTime? CreatedTime { get; set; }

    public bool? Active { get; set; }
    [MaxLength(50)]
    public string Remark { get; set; } = "";

    public bool External { get; set; }
    [RegularExpression(@"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$",
             ErrorMessage = "Password should have minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter and 1 number.")]
    public string Password { get; set; } = "";

    public string PasswordHash { get; set; } = "";

    public virtual ICollection<GlobalAppUserRoles> GlobalAppUserRoles { get; } = new List<GlobalAppUserRoles>();
}