// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SCMDWH.Shared.Models;

public partial class PlanningLoading
{
    public int Id { get; set; }

    public string Plant { get; set; }

    public string Year { get; set; }

    public string Month { get; set; }

    public string Week { get; set; }

    public string Customer { get; set; }

    public string Tpvdmodel { get; set; }

    public string Ctv { get; set; }

    public int? Quantity { get; set; }

    public string System { get; set; }

    public string Project { get; set; }

    public string Inch { get; set; }

    public string Category { get; set; }

    public string ProductType { get; set; }

    public string Factory { get; set; }

    public string FileName { get; set; }

    public DateTime? LoadingDate { get; set; }

    public string LoadingOwner { get; set; }
}