 // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace SCMDWH.Shared.Models;

public  class SoModuleGroupColumn
{
    public long Id { get; set; }

    public string? UserName { get; set; }

    public string? MainScreenColumn { get; set; }

    public bool Hidden { get; set; }

    public int? OrderColumn { get; set; }

    public int? ColumnWidth { get; set; }

    public string? PlHeader { get; set; }


}