//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMDWH.Client.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CultureExample2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureExample2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCMDWH.Client.Shared.CultureExample2", typeof(CultureExample2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wprowadzenia awizacji.
        /// </summary>
        public static string lbAdDate {
            get {
                return ResourceManager.GetString("lbAdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data awizacji .
        /// </summary>
        public static string lbAdDateNowy {
            get {
                return ResourceManager.GetString("lbAdDateNowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodane przez.
        /// </summary>
        public static string lbAddbyUser {
            get {
                return ResourceManager.GetString("lbAddbyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie nowego przewoźnika.
        /// </summary>
        public static string lbAddNewCurrier {
            get {
                return ResourceManager.GetString("lbAddNewCurrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status GR.
        /// </summary>
        public static string lbAddNewGRStatus {
            get {
                return ResourceManager.GetString("lbAddNewGRStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        public static string lbAddnewitem {
            get {
                return ResourceManager.GetString("lbAddnewitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy dostawca.
        /// </summary>
        public static string lbAddNewSeneder {
            get {
                return ResourceManager.GetString("lbAddNewSeneder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIejsce rozładunku.
        /// </summary>
        public static string lbAddNewUnloadingPlace {
            get {
                return ResourceManager.GetString("lbAddNewUnloadingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rzeczywista data przyjazdu (ATA).
        /// </summary>
        public static string lbAta {
            get {
                return ResourceManager.GetString("lbAta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rzeczywisty czas przyjazdu.
        /// </summary>
        public static string lbAtaDateTime {
            get {
                return ResourceManager.GetString("lbAtaDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rzeczywisty czas przyjazdu.
        /// </summary>
        public static string lbAtaTime {
            get {
                return ResourceManager.GetString("lbAtaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rzeczywista data przyjazdu (ATA).
        /// </summary>
        public static string lbAtaTimeDate {
            get {
                return ResourceManager.GetString("lbAtaTimeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wywołujący na załadunek.
        /// </summary>
        public static string lbCallBy {
            get {
                return ResourceManager.GetString("lbCallBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezygnuj.
        /// </summary>
        public static string lbCancel {
            get {
                return ResourceManager.GetString("lbCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samochody.
        /// </summary>
        public static string lbCarAdvice {
            get {
                return ResourceManager.GetString("lbCarAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przewoźnik.
        /// </summary>
        public static string lbCarriers {
            get {
                return ResourceManager.GetString("lbCarriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient.
        /// </summary>
        public static string lbClient {
            get {
                return ResourceManager.GetString("lbClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolumny.
        /// </summary>
        public static string lbColumns {
            get {
                return ResourceManager.GetString("lbColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontener.
        /// </summary>
        public static string lbContainer {
            get {
                return ResourceManager.GetString("lbContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakość kontener.
        /// </summary>
        public static string lbContainerQ {
            get {
                return ResourceManager.GetString("lbContainerQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiuj.
        /// </summary>
        public static string lbCopy {
            get {
                return ResourceManager.GetString("lbCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista przewoźników.
        /// </summary>
        public static string lbCurrierList {
            get {
                return ResourceManager.GetString("lbCurrierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klienci.
        /// </summary>
        public static string lbCustomers {
            get {
                return ResourceManager.GetString("lbCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń wszystko.
        /// </summary>
        public static string lbDeleteAll {
            get {
                return ResourceManager.GetString("lbDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string lbDestination {
            get {
                return ResourceManager.GetString("lbDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest. name.
        /// </summary>
        public static string lbDestinationName {
            get {
                return ResourceManager.GetString("lbDestinationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dest. Sap Id.
        /// </summary>
        public static string lbDestinationSapId {
            get {
                return ResourceManager.GetString("lbDestinationSapId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowniki FG.
        /// </summary>
        public static string lbDictionary {
            get {
                return ResourceManager.GetString("lbDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowniki GR.
        /// </summary>
        public static string lbDictionaryGR {
            get {
                return ResourceManager.GetString("lbDictionaryGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer doku.
        /// </summary>
        public static string lbDock {
            get {
                return ResourceManager.GetString("lbDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na prawdę chcesz usunąć? Ta czynność jest nieodwracalna!.
        /// </summary>
        public static string lbDoYouRealyDelete {
            get {
                return ResourceManager.GetString("lbDoYouRealyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane kierowcy się nie zgadzają!.
        /// </summary>
        public static string lbDriverMatchError {
            get {
                return ResourceManager.GetString("lbDriverMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane Kierowcy z ochrony.
        /// </summary>
        public static string lbDriverS {
            get {
                return ResourceManager.GetString("lbDriverS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane Kierowcy z magazynu.
        /// </summary>
        public static string lbDriverWH {
            get {
                return ResourceManager.GetString("lbDriverWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja.
        /// </summary>
        public static string lbEdit {
            get {
                return ResourceManager.GetString("lbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja przewoźnika.
        /// </summary>
        public static string lbEditCurrier {
            get {
                return ResourceManager.GetString("lbEditCurrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja fatury GR.
        /// </summary>
        public static string lbEditNewTruckItem {
            get {
                return ResourceManager.GetString("lbEditNewTruckItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina wjazdu.
        /// </summary>
        public static string lbEnTime {
            get {
                return ResourceManager.GetString("lbEnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba kontaktowa ochrona.
        /// </summary>
        public static string lbEntryByS {
            get {
                return ResourceManager.GetString("lbEntryByS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba kontaktowa magazyn.
        /// </summary>
        public static string lbEntrybyWH {
            get {
                return ResourceManager.GetString("lbEntrybyWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zly format daty!.
        /// </summary>
        public static string lberrorDateTime {
            get {
                return ResourceManager.GetString("lberrorDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontenery E-Shipping.
        /// </summary>
        public static string lbEshipingContainers {
            get {
                return ResourceManager.GetString("lbEshipingContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awizowana data przyjazdu (ETD).
        /// </summary>
        public static string lbEtdDate {
            get {
                return ResourceManager.GetString("lbEtdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awizowana godzina przyjazdu (ETD).
        /// </summary>
        public static string lbEtdTime {
            get {
                return ResourceManager.GetString("lbEtdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export do Excela.
        /// </summary>
        public static string lbExportExcel {
            get {
                return ResourceManager.GetString("lbExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje ogólne.
        /// </summary>
        public static string lbGeneralInfo {
            get {
                return ResourceManager.GetString("lbGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane magazynu.
        /// </summary>
        public static string lbGeneralWarehouseInfoprmation {
            get {
                return ResourceManager.GetString("lbGeneralWarehouseInfoprmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusy GR.
        /// </summary>
        public static string lbGrCarStatus {
            get {
                return ResourceManager.GetString("lbGrCarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostawca.
        /// </summary>
        public static string lbGrSender {
            get {
                return ResourceManager.GetString("lbGrSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce rozładunku.
        /// </summary>
        public static string lbGrUnloadingPlace {
            get {
                return ResourceManager.GetString("lbGrUnloadingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolumny ukryte.
        /// </summary>
        public static string lbHiddens {
            get {
                return ResourceManager.GetString("lbHiddens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string lbHome {
            get {
                return ResourceManager.GetString("lbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura.
        /// </summary>
        public static string lbInvoice {
            get {
                return ResourceManager.GetString("lbInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data opuszczenia doku.
        /// </summary>
        public static string lbleftdockdate {
            get {
                return ResourceManager.GetString("lbleftdockdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string lbLoadingMemu {
            get {
                return ResourceManager.GetString("lbLoadingMemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsca załadunku.
        /// </summary>
        public static string lbLoadingplaces {
            get {
                return ResourceManager.GetString("lbLoadingplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        public static string lbLoggeduser {
            get {
                return ResourceManager.GetString("lbLoggeduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiał.
        /// </summary>
        public static string lbMaterial {
            get {
                return ResourceManager.GetString("lbMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakość materiał.
        /// </summary>
        public static string lbMaterialQ {
            get {
                return ResourceManager.GetString("lbMaterialQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing qty..
        /// </summary>
        public static string lbMissingQty {
            get {
                return ResourceManager.GetString("lbMissingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        public static string lbNew {
            get {
                return ResourceManager.GetString("lbNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teraz.
        /// </summary>
        public static string lbNow {
            get {
                return ResourceManager.GetString("lbNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer PO.
        /// </summary>
        public static string lbOrderNo {
            get {
                return ResourceManager.GetString("lbOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date.
        /// </summary>
        public static string lbOriginalDeliveryDate {
            get {
                return ResourceManager.GetString("lbOriginalDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista palet.
        /// </summary>
        public static string lbPalletList {
            get {
                return ResourceManager.GetString("lbPalletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr palety.
        /// </summary>
        public static string lbPalletNo {
            get {
                return ResourceManager.GetString("lbPalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość na palecie.
        /// </summary>
        public static string lbPalletQty {
            get {
                return ResourceManager.GetString("lbPalletQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data załądunku.
        /// </summary>
        public static string lbPickingdate {
            get {
                return ResourceManager.GetString("lbPickingdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lbPickingstatus {
            get {
                return ResourceManager.GetString("lbPickingstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez statusu SENT.
        /// </summary>
        public static string lbPickingstatusCheckBox {
            get {
                return ResourceManager.GetString("lbPickingstatusCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez statusu ulokowane.
        /// </summary>
        public static string lbPickingstatusgRCheckBox {
            get {
                return ResourceManager.GetString("lbPickingstatusgRCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas załadunku.
        /// </summary>
        public static string lbPickingtime {
            get {
                return ResourceManager.GetString("lbPickingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista aut FG.
        /// </summary>
        public static string lbPlan {
            get {
                return ResourceManager.GetString("lbPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista aut GR.
        /// </summary>
        public static string lbPlanGR {
            get {
                return ResourceManager.GetString("lbPlanGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numery rejestracyjne pojazdu.
        /// </summary>
        public static string lbPlates {
            get {
                return ResourceManager.GetString("lbPlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numery pojazdu są niezgodne!.
        /// </summary>
        public static string lbPlatesMatchError {
            get {
                return ResourceManager.GetString("lbPlatesMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpierw wybierz wysyłkę!.
        /// </summary>
        public static string lbPleaseSelectRow {
            get {
                return ResourceManager.GetString("lbPleaseSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Pr / PO.
        /// </summary>
        public static string lbPoPrList {
            get {
                return ResourceManager.GetString("lbPoPrList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydruk.
        /// </summary>
        public static string lbPrintWH {
            get {
                return ResourceManager.GetString("lbPrintWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string lbProduct {
            get {
                return ResourceManager.GetString("lbProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string lbQty {
            get {
                return ResourceManager.GetString("lbQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość.
        /// </summary>
        public static string lbQuality {
            get {
                return ResourceManager.GetString("lbQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import PO .
        /// </summary>
        public static string lbReadExcelSO {
            get {
                return ResourceManager.GetString("lbReadExcelSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyczyna.
        /// </summary>
        public static string lbReason {
            get {
                return ResourceManager.GetString("lbReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer referencyjny.
        /// </summary>
        public static string lbReference {
            get {
                return ResourceManager.GetString("lbReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string lbRemark {
            get {
                return ResourceManager.GetString("lbRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi ochrony.
        /// </summary>
        public static string lbRemarksS {
            get {
                return ResourceManager.GetString("lbRemarksS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi magazynu.
        /// </summary>
        public static string lbRemarkWH {
            get {
                return ResourceManager.GetString("lbRemarkWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lbRoles {
            get {
                return ResourceManager.GetString("lbRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wierszy na stronie.
        /// </summary>
        public static string lbRowPerPage {
            get {
                return ResourceManager.GetString("lbRowPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data skanowania.
        /// </summary>
        public static string lbScanneddate {
            get {
                return ResourceManager.GetString("lbScanneddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina skanowania.
        /// </summary>
        public static string lbScannedtime {
            get {
                return ResourceManager.GetString("lbScannedtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM Narzędzia.
        /// </summary>
        public static string lbScmTools {
            get {
                return ResourceManager.GetString("lbScmTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string lbSearch {
            get {
                return ResourceManager.GetString("lbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ochrona.
        /// </summary>
        public static string lbSecurity {
            get {
                return ResourceManager.GetString("lbSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane ochrony.
        /// </summary>
        public static string lbSecurityEntryInfo {
            get {
                return ResourceManager.GetString("lbSecurityEntryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje ochrony.
        /// </summary>
        public static string lbSecurityinfo {
            get {
                return ResourceManager.GetString("lbSecurityinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoby ochrony.
        /// </summary>
        public static string lbSecuritypersons {
            get {
                return ResourceManager.GetString("lbSecuritypersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostawca.
        /// </summary>
        public static string lbSender {
            get {
                return ResourceManager.GetString("lbSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer wysyłki.
        /// </summary>
        public static string lbShipment {
            get {
                return ResourceManager.GetString("lbShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik i hasło  .
        /// </summary>
        public static string lbSignIn {
            get {
                return ResourceManager.GetString("lbSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string lbSingIn {
            get {
                return ResourceManager.GetString("lbSingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO.
        /// </summary>
        public static string lbSo {
            get {
                return ResourceManager.GetString("lbSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody status.
        /// </summary>
        public static string lbStatuscodes {
            get {
                return ResourceManager.GetString("lbStatuscodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość całkowita.
        /// </summary>
        public static string lbTotalQty {
            get {
                return ResourceManager.GetString("lbTotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wjazdu do TPV.
        /// </summary>
        public static string lbTPVEntrydate {
            get {
                return ResourceManager.GetString("lbTPVEntrydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas wjazdu do TPV.
        /// </summary>
        public static string lbTPVEntrytime {
            get {
                return ResourceManager.GetString("lbTPVEntrytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wyjazdu z TPV.
        /// </summary>
        public static string lbTPVExitdate {
            get {
                return ResourceManager.GetString("lbTPVExitdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas wyjazdu z TPV.
        /// </summary>
        public static string lbTpvExitTime {
            get {
                return ResourceManager.GetString("lbTpvExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numery rejestracyjne pojazdu z magazynu.
        /// </summary>
        public static string lbTruckplatesWH {
            get {
                return ResourceManager.GetString("lbTruckplatesWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samochód.
        /// </summary>
        public static string lbTruckType {
            get {
                return ResourceManager.GetString("lbTruckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista typów samochodów .
        /// </summary>
        public static string lbTruckTypes {
            get {
                return ResourceManager.GetString("lbTruckTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj plik.
        /// </summary>
        public static string lbUploadFiles {
            get {
                return ResourceManager.GetString("lbUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        public static string lbusername {
            get {
                return ResourceManager.GetString("lbusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolumny widoczne .
        /// </summary>
        public static string lbVisible {
            get {
                return ResourceManager.GetString("lbVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn.
        /// </summary>
        public static string lbWarehouse {
            get {
                return ResourceManager.GetString("lbWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn dane wysyłki.
        /// </summary>
        public static string lbWarehouseinformation {
            get {
                return ResourceManager.GetString("lbWarehouseinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string lbWeek {
            get {
                return ResourceManager.GetString("lbWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelecenia produkcyjne.
        /// </summary>
        public static string lbWorkOrder {
            get {
                return ResourceManager.GetString("lbWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Złe hasło lub nazwa użytkowanika.
        /// </summary>
        public static string lbWrongpassuser {
            get {
                return ResourceManager.GetString("lbWrongpassuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko dla pracowników ochrony .
        /// </summary>
        public static string lbYouMustBeSECURITY {
            get {
                return ResourceManager.GetString("lbYouMustBeSECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko dla pracowników magazynu.
        /// </summary>
        public static string lbYoumustbeWH {
            get {
                return ResourceManager.GetString("lbYoumustbeWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina opuszcz. doku.
        /// </summary>
        public static string leftdocktime {
            get {
                return ResourceManager.GetString("leftdocktime", resourceCulture);
            }
        }
    }
}
