//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMDWH.Client.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CultureExample2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureExample2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCMDWH.Client.Shared.CultureExample2", typeof(CultureExample2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polskie default .
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas awizacji.
        /// </summary>
        public static string lbAdDate {
            get {
                return ResourceManager.GetString("lbAdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ata.
        /// </summary>
        public static string lbAta {
            get {
                return ResourceManager.GetString("lbAta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Ata czas.
        /// </summary>
        public static string lbAtaDateTime {
            get {
                return ResourceManager.GetString("lbAtaDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ata godziny .
        /// </summary>
        public static string lbAtaTime {
            get {
                return ResourceManager.GetString("lbAtaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Ata .
        /// </summary>
        public static string lbAtaTimeDate {
            get {
                return ResourceManager.GetString("lbAtaTimeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wywołujący .
        /// </summary>
        public static string lbCallBy {
            get {
                return ResourceManager.GetString("lbCallBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezygnuj.
        /// </summary>
        public static string lbCancel {
            get {
                return ResourceManager.GetString("lbCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samochody .
        /// </summary>
        public static string lbCarAdvice {
            get {
                return ResourceManager.GetString("lbCarAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przewoźnicy.
        /// </summary>
        public static string lbCarriers {
            get {
                return ResourceManager.GetString("lbCarriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient.
        /// </summary>
        public static string lbClient {
            get {
                return ResourceManager.GetString("lbClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolumny .
        /// </summary>
        public static string lbColumns {
            get {
                return ResourceManager.GetString("lbColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klienci.
        /// </summary>
        public static string lbCustomers {
            get {
                return ResourceManager.GetString("lbCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Dest.
        /// </summary>
        public static string lbDestination {
            get {
                return ResourceManager.GetString("lbDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowniki.
        /// </summary>
        public static string lbDictionary {
            get {
                return ResourceManager.GetString("lbDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dok.
        /// </summary>
        public static string lbDock {
            get {
                return ResourceManager.GetString("lbDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierowca och..
        /// </summary>
        public static string lbDriverS {
            get {
                return ResourceManager.GetString("lbDriverS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierowca-magazyn.
        /// </summary>
        public static string lbDriverWH {
            get {
                return ResourceManager.GetString("lbDriverWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina wjazdu.
        /// </summary>
        public static string lbEnTime {
            get {
                return ResourceManager.GetString("lbEnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wjazd - ochrona.
        /// </summary>
        public static string lbEntryByS {
            get {
                return ResourceManager.GetString("lbEntryByS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --lbEntrybyWH.
        /// </summary>
        public static string lbEntrybyWH {
            get {
                return ResourceManager.GetString("lbEntrybyWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zly format daty.
        /// </summary>
        public static string lberrorDateTime {
            get {
                return ResourceManager.GetString("lberrorDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --ETD Date.
        /// </summary>
        public static string lbEtdDate {
            get {
                return ResourceManager.GetString("lbEtdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --ETD time.
        /// </summary>
        public static string lbEtdTime {
            get {
                return ResourceManager.GetString("lbEtdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn wyrobów gotowych.
        /// </summary>
        public static string lbGeneralWarehouseInfoprmation {
            get {
                return ResourceManager.GetString("lbGeneralWarehouseInfoprmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string lbHome {
            get {
                return ResourceManager.GetString("lbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data opuszczenia doku.
        /// </summary>
        public static string lbleftdockdate {
            get {
                return ResourceManager.GetString("lbleftdockdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsca załadunku.
        /// </summary>
        public static string lbLoadingplaces {
            get {
                return ResourceManager.GetString("lbLoadingplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzytkownik.
        /// </summary>
        public static string lbLoggeduser {
            get {
                return ResourceManager.GetString("lbLoggeduser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        public static string lbNew {
            get {
                return ResourceManager.GetString("lbNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teraz.
        /// </summary>
        public static string lbNow {
            get {
                return ResourceManager.GetString("lbNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data załadunku.
        /// </summary>
        public static string lbPickingdate {
            get {
                return ResourceManager.GetString("lbPickingdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lbPickingstatus {
            get {
                return ResourceManager.GetString("lbPickingstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina załadunku.
        /// </summary>
        public static string lbPickingtime {
            get {
                return ResourceManager.GetString("lbPickingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista aut.
        /// </summary>
        public static string lbPlan {
            get {
                return ResourceManager.GetString("lbPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablice.
        /// </summary>
        public static string lbPlates {
            get {
                return ResourceManager.GetString("lbPlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakość.
        /// </summary>
        public static string lbQuality {
            get {
                return ResourceManager.GetString("lbQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przyczyna.
        /// </summary>
        public static string lbReason {
            get {
                return ResourceManager.GetString("lbReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer.
        /// </summary>
        public static string lbReference {
            get {
                return ResourceManager.GetString("lbReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi ochrona.
        /// </summary>
        public static string lbRemarksS {
            get {
                return ResourceManager.GetString("lbRemarksS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn uwagi.
        /// </summary>
        public static string lbRemarkWH {
            get {
                return ResourceManager.GetString("lbRemarkWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lbRoles {
            get {
                return ResourceManager.GetString("lbRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data skanowania.
        /// </summary>
        public static string lbScanneddate {
            get {
                return ResourceManager.GetString("lbScanneddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina skanowania.
        /// </summary>
        public static string lbScannedtime {
            get {
                return ResourceManager.GetString("lbScannedtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string lbSearch {
            get {
                return ResourceManager.GetString("lbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ochrona.
        /// </summary>
        public static string lbSecurity {
            get {
                return ResourceManager.GetString("lbSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje Ochrony.
        /// </summary>
        public static string lbSecurityEntryInfo {
            get {
                return ResourceManager.GetString("lbSecurityEntryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje ochrony.
        /// </summary>
        public static string lbSecurityinfo {
            get {
                return ResourceManager.GetString("lbSecurityinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoby ochrony.
        /// </summary>
        public static string lbSecuritypersons {
            get {
                return ResourceManager.GetString("lbSecuritypersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysyłka.
        /// </summary>
        public static string lbShipment {
            get {
                return ResourceManager.GetString("lbShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkowanik i hasło  .
        /// </summary>
        public static string lbSignIn {
            get {
                return ResourceManager.GetString("lbSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wejście.
        /// </summary>
        public static string lbSingIn {
            get {
                return ResourceManager.GetString("lbSingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody status.
        /// </summary>
        public static string lbStatuscodes {
            get {
                return ResourceManager.GetString("lbStatuscodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wjazdu.
        /// </summary>
        public static string lbTPVEntrydate {
            get {
                return ResourceManager.GetString("lbTPVEntrydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas wjazdu.
        /// </summary>
        public static string lbTPVEntrytime {
            get {
                return ResourceManager.GetString("lbTPVEntrytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjazd dzień.
        /// </summary>
        public static string lbTPVExitdate {
            get {
                return ResourceManager.GetString("lbTPVExitdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjazd z TPV.
        /// </summary>
        public static string lbTpvExitTime {
            get {
                return ResourceManager.GetString("lbTpvExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablice-magazyn.
        /// </summary>
        public static string lbTruckplatesWH {
            get {
                return ResourceManager.GetString("lbTruckplatesWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samochód.
        /// </summary>
        public static string lbTruckType {
            get {
                return ResourceManager.GetString("lbTruckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        public static string lbusername {
            get {
                return ResourceManager.GetString("lbusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn.
        /// </summary>
        public static string lbWarehouse {
            get {
                return ResourceManager.GetString("lbWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazyn dane wysyłki .
        /// </summary>
        public static string lbWarehouseinformation {
            get {
                return ResourceManager.GetString("lbWarehouseinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Złe hasło lub nazwa użytkowanika.
        /// </summary>
        public static string lbWrongpassuser {
            get {
                return ResourceManager.GetString("lbWrongpassuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina opuszcz. doku.
        /// </summary>
        public static string leftdocktime {
            get {
                return ResourceManager.GetString("leftdocktime", resourceCulture);
            }
        }
    }
}
